### ISSUE TITLE
11. 좋아요 API

### ISSUE THREAD

**Issue by kurikame73** [GoungGoung-AI-Math/ProblemService#11]
## ISSUE
풀이, 질문, 답변 좋아요
아마 noSQL?

- 유저 동작
    - 로그인 한 유저
    - 풀이, 질문, 답변에 대한 리뷰 중 따봉 버튼을 클릭
    - 
- API 입출력
    - 입력
        - (풀이 아이디, 질문 아이디, 답변 아이디) 
        - 유저 정보(아이디)
    - 출력
        - 잘 처리했는지 안했는지 응답

## TASKS
- [ ] API 설계
- [ ] 유닛 테스트
- [ ] 통합 테스트
- [ ] 배포

**Comment by haxr369** [comment]
좋아요 같은 경우는 먼저 문제 서비스에서 유효성 검사를 진행한 후 유저 서비스로 add하도록 요청하기!

 - [x] 문제 서비스로 domainId와 domainType(ANSWER, QUESTION, REVIEW, ... )을 함께 전달하기
 - [x] 문제 서비스에 domainType에 domainId 값의 데이터가 존재하는지 확인
 - [ ] 유저 서비스로 좋아요 숫자 증가하도록 요청하기


## 유효성 검사 후 정상적으로 kafka 요청 보내기 성공


![Image](https://github.com/user-attachments/assets/a43ba445-5a81-423a-a367-ad7c786c0f52)

![Image](https://github.com/user-attachments/assets/86c393fd-0af5-41f6-b778-a45896423fe6)
