### ISSUE TITLE
6. 풀이 제출 시 비동기 GPT 채점 요청 API

### ISSUE THREAD

**Issue by kurikame73** [GoungGoung-AI-Math/ProblemService#6]
## ISSUE
풀이 제출 시 비동기적으로 GPT에 사용자 풀이에 대한 채점 요청 Request을 보내고 응답을 받아서 DB의 풀이에 상태 및 채점 결과 갱신
### 예상
Request : 사용자 정보, 문제 정보, 풀이 정보, 풀이 내용
Response: 202, 400, 200 
정답 여부, 채점 결과 상세

## ESTIMATE
3 ~ 4day

## TASKS
- [ ] 사진 풀이, 수식 풀이 테스트
- [ ] gpt 채점 상세 내용 받아오기 테스트
- [ ] gpt 채점 상세 내용에서 정답 여부 파싱 테스트
- [ ] API 설계
- [ ] 유닛 테스트
- [ ] 통합 테스트
- [ ] 배포
